- app/src/main/java/com/example/jaamebaade_client/model/Status.kt
- app/src/main/java/com/example/jaamebaade_client/view/SearchScreen.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/SearchViewModel.kt
> feature: add loading for search

- README.md
- app/src/main/java/com/example/jaamebaade_client/constants/AppRoutes.kt
- app/src/main/java/com/example/jaamebaade_client/dao/PoemDao.kt
- app/src/main/java/com/example/jaamebaade_client/model/PoemWithPoet.kt
- app/src/main/java/com/example/jaamebaade_client/repository/PoemRepository.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/Topbar.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/TopBarViewModel.kt
> feat: add random poem button

- app/src/main/java/com/example/jaamebaade_client/view/components/VerseItem.kt
> fix: huge improvements in highlight

- app/build.gradle.kts
- app/src/main/java/com/example/jaamebaade_client/AppModule.kt
- app/src/main/java/com/example/jaamebaade_client/AppNavHost.kt
- app/src/main/java/com/example/jaamebaade_client/api/AudioApiClient.kt
- app/src/main/java/com/example/jaamebaade_client/api/DictionaryApiClient.kt
- app/src/main/java/com/example/jaamebaade_client/api/SyncAudioClient.kt
- app/src/main/java/com/example/jaamebaade_client/api/response/AudioData.kt
- app/src/main/java/com/example/jaamebaade_client/api/response/AudioSyncResponse.kt
- app/src/main/java/com/example/jaamebaade_client/model/Status.kt
- app/src/main/java/com/example/jaamebaade_client/view/VersesScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/AudioMenu.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/VerseItem.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/SelectionOptionViewModel.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/VersesViewModel.kt
- gradle/libs.versions.toml
> Feature: show recited verse

- app/src/main/java/com/example/jaamebaade_client/AppNavHost.kt
- app/src/main/java/com/example/jaamebaade_client/api/AudioApiClient.kt
- app/src/main/java/com/example/jaamebaade_client/api/response/AudioData.kt
- app/src/main/java/com/example/jaamebaade_client/dao/PoemDao.kt
- app/src/main/java/com/example/jaamebaade_client/repository/PoemRepository.kt
- app/src/main/java/com/example/jaamebaade_client/ui/theme/Color.kt
- app/src/main/java/com/example/jaamebaade_client/view/VersesScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/AudioButton.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/AudioControlBar.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/AudioListScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/AudioMenu.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/Topbar.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/VersesPageHeader.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/AudioViewModel.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/VersesViewModel.kt
> feat: add music control panel

- app/src/main/java/com/example/jaamebaade_client/view/VersesScreen.kt
fixes crashes when song starts to play
> fix: add delay for loop + code refactor

- app/src/main/java/com/example/jaamebaade_client/view/VersesScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/PoetItem.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/SelectionBottomSheet.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/VerseItem.kt
> Feature:‌ selection for verses

- app/src/main/java/com/example/jaamebaade_client/view/components/Navbar.kt
> fix: fix navbar multiple clicks change view

- app/src/main/java/com/example/jaamebaade_client/AppNavHost.kt
- app/src/main/java/com/example/jaamebaade_client/MainActivity.kt
- app/src/main/java/com/example/jaamebaade_client/constants/AppRoutes.kt
- app/src/main/java/com/example/jaamebaade_client/repository/ThemeRepository.kt
- app/src/main/java/com/example/jaamebaade_client/ui/theme/AppThemeType.kt
- app/src/main/java/com/example/jaamebaade_client/utility/SharedPrefManager.kt
- app/src/main/java/com/example/jaamebaade_client/view/ChangeThemeScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/SettingsScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/SettingsItem.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/SettingsViewModel.kt
- app/src/main/java/com/example/jaamebaade_client/viewmodel/TopBarViewModel.kt
> feature: add theme toggle to settings

- app/src/main/java/com/example/jaamebaade_client/repository/ThemeRepository.kt
- app/src/main/java/com/example/jaamebaade_client/utility/SharedPrefManager.kt
- app/src/main/java/com/example/jaamebaade_client/view/ChangeThemeScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/VersesScreen.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/AudioButton.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/BookmarkList.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/HighlightList.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/PoetItem.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/Topbar.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/VerseItem.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/VerseTextField.kt
- app/src/main/java/com/example/jaamebaade_client/view/components/VersesPageHeader.kt
resolves #84 
resovles #85
resovles #86 
resovles #87 
resovles #88 
resovles #89
> Fix: small improvements in highlight, icons, ux, ui

- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/PoemDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/PoemRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/Topbar.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/TopBarViewModel.kt
- app/src/main/res/values/strings.xml
> fix: app no longer crashes when no poet is available

- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/VerseItem.kt
also animations for VerseItem have been improved.
resolves: #102
> fix: verse numbers are adjusted

- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/DownloadedPoetsScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/Topbar.kt
> fix: using os back button in DownloadedPoetsScreen now functions correctly

- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/SelectionBottomSheet.kt
> fix: word meaning text should be scrollable

- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/CommentDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/Comment.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/CommentRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/CommentsScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/CommentViewModel.kt
> fix: delete comment sometimes does not work

- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/SearchScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/SearchResultItem.kt
> feat: add color to search query in search results

- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/CategoryDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/VersePoemCategoriesPoet.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/CategoryRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/SearchScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/PoemTracePath.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/SearchBar.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/SearchResultItem.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/SearchViewModel.kt
> feat: redesign search page

- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/CommentDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/CommentPoemCategoriesPoet.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/CommentPoemPoet.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/VersePoemCategoriesPoet.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/CommentRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/FavoritesScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/CommentListItem.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/CommentsList.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/SearchResultItem.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/FavoritesViewModel.kt
> feat: add CommentsList to FavoritesScreen

- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/SearchScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/Navbar.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/SearchBar.kt
> fix: back button no longer resets states

- app/src/main/java/ir/jaamebaade/jaamebaade_client/AppNavHost.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/PoemDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/PoemWithFirstVerse.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/PoemRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/PoetCategoryPoemScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/CategoryItem.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/DownloadedPoet.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/PoemsListItem.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/PoetCategoryPoemViewModel.kt
> feat: add first verse to poemListItem

- app/schemas/ir.jaamebaade.jaamebaade_client.database.AppDatabase/4.json
- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/CategoryDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/PoemDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/database/AppDatabase.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/Category.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/CategoryRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/AdvancedRandomPoemOptions.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/CustomIconButton.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/ExpandableCheckbox.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/RandomPoemOptions.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/Topbar.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/DownloadedPoetViewModel.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/TopBarViewModel.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/wrapper/CategoryGraphNode.kt
- app/src/main/res/values/strings.xml
> feat: add advanced options for random poem

- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/BookmarkRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/BookmarkItem.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/BookmarkList.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/FavoritesViewModel.kt
> feat: add unbookmark button to bookmark list

- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/PoemScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/SearchScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/AudioListScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/Navbar.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/PoemScreenActionHeader.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/PoemScreenMoreOptionsMenu.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/PoemScreenPathHeader.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/Topbar.kt
- app/src/main/res/values/strings.xml
also fixed search result bold item incorrect change
> fix: minor style changes and bug fixes

- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/CategoryDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/PoemDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/VerseDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/CategoryRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/PoemRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/utility/ImportCsvData.kt
> fix: try to fix poet not being added after downloading

- app/src/main/java/ir/jaamebaade/jaamebaade_client/api/PoetApiClient.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/api/PoetApiService.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/DownloadablePoetsScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/PoetViewModel.kt
> feat: add pagination to downloadable poets

- app/schemas/ir.jaamebaade.jaamebaade_client.database.AppDatabase/6.json
- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/BookmarkDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/dao/HighlightDao.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/database/AppDatabase.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/Bookmark.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/Highlight.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/BookmarkRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/CommentsScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/HighlightList.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/VerseTextField.kt
> feat: add createdAt to highlight and bookmark

- app/build.gradle.kts
- app/schemas/ir.jaamebaade.jaamebaade_client.database.AppDatabase/7.json
- app/src/main/java/ir/jaamebaade/jaamebaade_client/AppNavHost.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/database/AppDatabase.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/Highlight.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/Poet.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/model/Verse.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/repository/PoetRepository.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/utility/ImportCsvData.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/DownloadablePoetsScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/PoemScreen.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/DownloadedPoet.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/HighlightList.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/view/components/PoetItem.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/PoemViewModel.kt
- app/src/main/java/ir/jaamebaade/jaamebaade_client/viewmodel/PoetViewModel.kt
- app/src/main/res/values/strings.xml
> refactor: rewrite download status handling
